[server]
enableStaticServing = true

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter_28pt-Thin.ttf"
style = "normal"
weight = "100"

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter_28pt-ExtraLight.ttf"
style = "normal"
weight = "200"

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter_28pt-Light.ttf"
style = "normal"
weight = "300"

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter_28pt-Regular.ttf"
style = "normal"
weight = "400"

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter_28pt-Medium.ttf"
style = "normal"
weight = "500"

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter_28pt-SemiBold.ttf"
style = "normal"
weight = "600"

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter_28pt-Bold.ttf"
style = "normal"
weight = "700"

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter_28pt-ExtraBold.ttf"
style = "normal"
weight = "800"

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter_28pt-Black.ttf"
style = "normal"
weight = "900"

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter_28pt-ThinItalic.ttf"
style = "italic"
weight = "100"

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter_28pt-ExtraLightItalic.ttf"
style = "italic"
weight = "200"

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter_28pt-LightItalic.ttf"
style = "italic"
weight = "300"

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter_28pt-Italic.ttf"
style = "italic"
weight = "400"

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter_28pt-MediumItalic.ttf"
style = "italic"
weight = "500"

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter_28pt-SemiBoldItalic.ttf"
style = "italic"
weight = "600"

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter_28pt-BoldItalic.ttf"
style = "italic"
weight = "700"

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter_28pt-ExtraBoldItalic.ttf"
style = "italic"
weight = "800"

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter_28pt-BlackItalic.ttf"
style = "italic"
weight = "900"

[theme]
base = "dark"
primaryColor = "#60b5ff"
backgroundColor = "#2a2a2a"
secondaryBackgroundColor = "#121212"
codeBackgroundColor = "#121212"
textColor = "#ffffff"
linkColor = "#60b5ff"
borderColor = "#7c7c7c"
showWidgetBorder = true
baseRadius = "0.3rem"
buttonRadius = "0.55rem"
font = "Inter"
headingFontWeights = [600, 500, 500, 500, 500, 500]
headingFontSizes = ["3rem", "2.5rem", "2.25rem", "2rem", "1.5rem"]
chartCategoricalColors = ["#ffc862", "#2d46b9", "#b49bc8"]

[theme.sidebar]
backgroundColor = "#121212"
secondaryBackgroundColor = "#000000"
codeBackgroundColor = "#2a2a2a"
borderColor = "#696969"